### PR TITLE
Further Python 3 compatibility 

### PR DESCRIPTION
**Pull request by penenkel**
Based on commit ca41ee8 (post Python 3.4 support, but pre PyQt5 support, as there is no PyQt5 conda package for Windows atm) I'm trying to enhance Python 3 compatibility:
- [x] replace outdated distutils dependency with setuptools
- [ ] fix 2to3 related list vs iterator bugs in .enaml  files 
  - [x] filter (one occurrence)
  - [x] map (no occurrence)
  - [ ] others?
- [ ] Python 3.4 ast grammar changes
  - [ ] ClassDef now requires a keywords argument (and perhaps others) (compare [ast 3.4](https://docs.python.org/3.4/library/ast.html) with [ast 2.7](https://docs.python.org/2.7/library/ast.html))
    I'm not sure how to fix that, do you know what to do here?
  - [ ] others?
- [ ] Python 3.5 compatibility (This is rather more complex, I think)
  - [x] update byteplay.py (SETUP_WITH is now split into two)
  - [ ] probably many more

### CODE REVIEW

**Comment by peterazmanov** [comment]
Your changes LGTM. Do you consider to work on other enhancements you mentioned? I can merge your pull request now but it'll close it. As an alternative we can open an issue for further work and discussion.

**Comment by peterazmanov** [comment]
I created this fork to continue the work on Python 3 compatibility in nucleic/enaml. Seems that contributors of main repository are not interested in this work now. All the changes that I made were little more than 'bugfixes' for non-working-under-py3k code :). I do not consider myself Python expert, there are low-level changes, which require thorough code review.

Application on which I work now is intended to work under Python 3.4, that's why I didn't support changes of `SETUP_WITH` in byteplay.py. I don't have classes in my enaml code, and that's the reason behind not fixed `ClassDef` in parser.py.

The changes I made are not suffiecient for full fledged Python 3.4(5) support. AFAIK the main obstacle is that we don't have parser source code, so we can't change grammar of python code in enaml code.

**Comment by penenkel** [comment]
I intend to use enaml in a project, so I will undoubtedly run into more issues along the way. So It would probably best if we could open one (or more issues). ATM issues appear to be deactivated on your fork. I think it would be best to create at least  to separate issues, one for py34 and one for py35.
The other stuff is minor and can be merged now.
Regarding the parser source code: I think lexer.py and parser.py ARE the parser grammar, thats how PLY works.

**Comment by peterazmanov** [comment]
@penenkel  I enabled issues. Thanks for clarification about parser, I didn't understand how PLY works. )

**Comment by peterazmanov** [comment]
@penenkel, I synced fork with https://github.com/nucleic/enaml/tree/master and moved Qt5 support to separate branch https://github.com/peterazmanov/enaml/tree/Qt5, created Milestone to gather Issues related to Python 3 support and added several issues I'm aware of. If you create Issues you listed above ('ClassDef keywords' and 'byteplay.py Python 3.5 SETUP-WITH'), i'll merge your pull request to master and qt5-branch OR if it's ok with you I can create these issues myself.

**Comment by penenkel** [comment]
@peterazmanov, you may create the relevant issues as you see fit. Basically only two of the open points above are truly relevant: 1) SETUP_WITH for py3.5 compatibility and 2) ClassDef  Grammar change for py3.x  compatibility.

I'm not quite certain if maintaining a shared codebase for py2 and py3 support is feasible in light of the many lowlevel manipulations ENAML requires, but if you think it's doable I'm all for it :+1: 

For Qt support, one could consider a similar approach. Take a look how it is done in [Spyder](https://github.com/spyder-ide/qtpy). One the other hand I haven't much experience with Qt, so I can't really say if it is feasible.

(Also I'm rather abusing this pull-request with this general purpose discussion ;-)

**Comment by peterazmanov** [comment]
@penenkel, I agree issues you mentioned are of high priority. I'll create standalone issues and merge your pull request.

Python 2+3 shared codebase: it's certainly harder than shared codebase for Qt4 and Qt5, but if it's done the fork will be ready for pull request to upstream repo. It is low priority task now, but support only for Python 3 could be a reason not to merge...

**Comment by peterazmanov** [comment]
@penenkel, based on Python docs [3.4](https://docs.python.org/3.4/library/dis.html)->[3.5](https://docs.python.org/3.5/library/dis.html): `SETUP_WITH` didn't change, it was `WITH_CLEANUP`. So I created issue about `WITH_CLEANUP`...

**Pull request merged**
